name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: wurstmeister/zookeeper
        ports: 
          - 2181:2181

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Configuration.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Configuration.sln --no-restore --verbosity normal
