name: pack and push

on:
  push:
    branches: [ master ]
    paths:
     - 'Directory.Build.props'

jobs:
  pack_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Configuration.sln -c Release --no-restore      
    - name: Pack
      run: dotnet pack Configuration.sln --no-build -c Release -o artifacts
    - name: Push
      run: dotnet nuget push artifacts/**.nupkg -s https://www.nuget.org -k ${{secrets.NUGET_TOKEN}}
